language: swift
osx_image: xcode10

env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool

global:
- PROJECT=CollectionViewTools.xcodeproj
- IOS_FRAMEWORK_SCHEME="CollectionViewTools"
- IOS_SDK=iphonesimulator

script:
- set -o pipefail
- xcodebuild -project "$PROJECT" -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" build test | xcpretty -c --test --color
